function modelLimits = generateModelLimits()
% Oracle model limits computed by training on the test sequence itself.
% Uses explicit baseline parameters for a true upper bound.

load('perClassParams.mat', 'datasets', 'benchmarks');

% Load the explicit baseline parameters for each dataset
baselineParams = [];
if isfile('datasetParamsNoMix.mat')
    data = load('datasetParamsNoMix.mat');
    if isfield(data, 'datasetParams')
        baselineParams = data.datasetParams;
    end
end

modelLimits = struct('name', {}, 'benchmark', {}, 'bitsPerSymbol', {}, 'params', {});

for di = 1:numel(datasets)
    name = datasets{di};
    testFile = ['sequence_' name '_test.mat'];
    fprintf('Generating model limit for %s using %s as both train and test...\n', name, testFile);

    % Use explicit baseline parameters if available, otherwise fall back to autoTune
    useExplicitParams = ~isempty(baselineParams);

    if useExplicitParams
        % Find matching dataset in baseline params
        idx = find(strcmp({baselineParams.name}, name), 1);
        if ~isempty(idx)
            bp = baselineParams(idx).params;
            fprintf('  Using explicit params: k=%d wb=%.2f ps=%.3f g=%.1f mix=%.2f\n', ...
                bp.k, bp.weightBase, bp.priorScale, bp.gamma, bp.mixAlpha);
            [bitsPerSymbol, params] = expmodelTrie(name, ...
                'trainFileOverride', testFile, ...
                'testFileOverride', testFile, ...
                'autoTune', false, ...
                'useDatasetTuning', false, ...
                'usePerClassTuning', false, ...
                'useGlobalDefault', false, ...
                'k', bp.k, ...
                'weightBase', bp.weightBase, ...
                'priorScale', bp.priorScale, ...
                'gamma', bp.gamma, ...
                'mixAlpha', bp.mixAlpha, ...
                'shallowK', bp.shallowK);
        else
            % Fallback to autoTune if dataset not found in baseline
            fprintf('  Dataset not found in baseline params, using autoTune\n');
            [bitsPerSymbol, params] = expmodelTrie(name, ...
                'trainFileOverride', testFile, ...
                'testFileOverride', testFile, ...
                'autoTune', true, ...
                'useDatasetTuning', false, ...
                'usePerClassTuning', false, ...
                'useGlobalDefault', false);
        end
    else
        % No baseline params available, use autoTune
        fprintf('  No baseline params found, using autoTune\n');
        [bitsPerSymbol, params] = expmodelTrie(name, ...
            'trainFileOverride', testFile, ...
            'testFileOverride', testFile, ...
            'autoTune', true, ...
            'useDatasetTuning', false, ...
            'usePerClassTuning', false, ...
            'useGlobalDefault', false);
    end

    modelLimits(di).name = name;
    modelLimits(di).benchmark = benchmarks(di);
    modelLimits(di).bitsPerSymbol = bitsPerSymbol;
    modelLimits(di).params = params;

    fprintf('  limit=%.4f bits/symbol (benchmark=%.4f)\n', bitsPerSymbol, benchmarks(di));
end

save('modelLimits.mat', 'modelLimits', 'datasets', 'benchmarks');
end
